CURRENT TIME 2024-01-19 14:00:09
ON VM
Fetching matchups for 2024-01-19..
Traceback (most recent call last):
  File "/home/nicoloruffini/twitterBot/main.py", line 9, in <module>
    TwitterBot(dry_run=False, vm=True).post_tweet()
  File "/home/nicoloruffini/twitterBot/twitter.py", line 99, in post_tweet
    text = self.run_model()
  File "/home/nicoloruffini/twitterBot/twitter.py", line 55, in run_model
    m = Model(vm=True)
  File "/home/nicoloruffini/twitterBot/nba_models/get_picks.py", line 19, in __init__
    self.matchups = self.nba.get_matchups()
  File "/home/nicoloruffini/twitterBot/nba_models/nba_scraper/scraper.py", line 292, in get_matchups
    lines_dic["spread"] = spread.replace(temp, tags[temp])
KeyError: 'N/A'
